// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace tensaisses.Migrations
{
    [DbContext(typeof(ProjectEnvironmentDbContext))]
    [Migration("20221229135324_projectenv1stmigCreate")]
    partial class projectenv1stmigCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tensai_sses.Models.ProjectEnvironments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("env_id")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("project_id")
                        .HasColumnType("integer");

                    b.Property<int>("updated_by_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("env_id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.HasIndex("project_id");

                    b.ToTable("project_environments");
                });

            modelBuilder.Entity("tensai_sses.Models.ProjectEnvironments", b =>
                {
                    b.HasOne("tensai_sses.Models.Environments", "environments")
                        .WithMany()
                        .HasForeignKey("env_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tensai_sses.Models.Project", "projects")
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("environments");

                    b.Navigation("projects");
                });
#pragma warning restore 612, 618
        }
    }
}
