// // <auto-generated />
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Migrations;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
// using tensai_sses.Data;

// #nullable disable

// namespace tensaisses.Migrations
// {
//     [DbContext(typeof(MyDbContext))]
//     [Migration("20221222110511_ThirdCreate")]
//     partial class ThirdCreate
//     {
//         /// <inheritdoc />
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "7.0.1")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 63);

//             NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

//             modelBuilder.Entity("tensai_sses.Models.Environments", b =>
//                 {
//                     b.Property<int>("id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("integer");

//                     NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

//                     b.Property<string>("description")
//                         .IsRequired()
//                         .HasColumnType("text");

//                     b.Property<bool>("is_active")
//                         .HasColumnType("boolean");

//                     b.Property<string>("name")
//                         .IsRequired()
//                         .HasColumnType("text");

//                     b.Property<string>("update_on")
//                         .IsRequired()
//                         .HasColumnType("text");

//                     b.Property<string>("updated_by_id")
//                         .IsRequired()
//                         .HasColumnType("text");

//                     b.Property<string>("version")
//                         .IsRequired()
//                         .HasColumnType("text");

//                     b.HasKey("id");

//                     b.ToTable("deployable_environments");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
