// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace tensaisses.Migrations
{
    [DbContext(typeof(StageToolDbContext))]
    [Migration("20221228114105_1stmigstagetoolCreate")]
    partial class _1stmigstagetoolCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tensai_sses.Models.PipelineStages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("updated_by_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("PipelineStages");
                });

            modelBuilder.Entity("tensai_sses.Models.StageTool", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("access_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cred_secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cred_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cred_user")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("stage_id")
                        .HasColumnType("integer");

                    b.Property<int>("tool_id")
                        .HasColumnType("integer");

                    b.Property<int>("updated_by_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.HasIndex("stage_id");

                    b.HasIndex("tool_id");

                    b.ToTable("stages_tools_mapping");
                });

            modelBuilder.Entity("tensai_sses.Models.SupportTools", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("SupportTools");
                });

            modelBuilder.Entity("tensai_sses.Models.StageTool", b =>
                {
                    b.HasOne("tensai_sses.Models.PipelineStages", "pipelinestages")
                        .WithMany()
                        .HasForeignKey("stage_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tensai_sses.Models.SupportTools", "supporttools")
                        .WithMany()
                        .HasForeignKey("tool_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pipelinestages");

                    b.Navigation("supporttools");
                });
#pragma warning restore 612, 618
        }
    }
}
