// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace tensaisses.Migrations
{
    [DbContext(typeof(ProjectDBContext))]
    [Migration("20221229135137_project1stmigCreatekar")]
    partial class project1stmigCreatekar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tensai_sses.Models.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("artifactory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("build")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("code_analysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dependency_check")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("deploy")
                        .HasColumnType("boolean");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("scm_tool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("updated_by_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("project_main");
                });
#pragma warning restore 612, 618
        }
    }
}
