// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace tensaisses.Migrations.PipelineHistoryDb
{
    [DbContext(typeof(PipelineHistoryDbContext))]
    [Migration("20230116081334_PipelineHistorySecondCreate")]
    partial class PipelineHistorySecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tensai_sses.Models.PipelineHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("applicationURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("branch_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("build_number")
                        .HasColumnType("integer");

                    b.Property<string>("environment_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("job_status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("pipeline_history");
                });
#pragma warning restore 612, 618
        }
    }
}
